[package]
name = "library-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
diesel = "2.2.6"
serde = { version = "1.0", features = ["derive"] }

[dependencies.uuid]
version = "1.11.1"
features = [ "v4" ]
