[package]
name = "library-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
diesel = "2.2.6"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.11.1", features = [ "v4" ] }
libsqlite3-sys = { version = "0.29", features = ["bundled"] }
